### ISSUE TITLE
pypi project

### ISSUE THREAD

**Issue by wojdyr** [eggplants/gemmi-stubs#3]
Hi @eggplants
I'll add type stubs to gemmi in the next release, in the same package as gemmi.
I thought you could remove it from PyPI to avoid confusion.
I mean this project: https://pypi.org/project/gemmi-stubs
Thanks for looking into it.
Marcin

**Comment by eggplants** [comment]
Sorry for my slow response. I will add some description to the readme and archive this repo.

> I thought you could remove it from PyPI to avoid confusion.

I won't do that. Some private and stale projects are depending on gemmi-stubs. If I remove from PyPI they will be unable to build anymore.

**Comment by eggplants** [comment]
Not yet?
https://github.com/project-gemmi/gemmi/issues/293
